spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          # issuer-uri 활성화 시,
          # OAuth2 자동설정 클래스가 나머지 엔드포인트에 요청을 보낸다.
          issuer-uri: "http://localhost:8080/realms/spring-msa-realm"
          jwk-set-uri: "http://localhost:8080/realms/spring-msa-realm/protocol/openid-connect/certs"

  # https://www.baeldung.com/spring-boot-application-context-exception
  # web-application-type: reactive 를 통해
  # Web MVC 의존성을 거부하도록 설정할 수 있다.
  # 하지만, Web MVC 의존성이 없는데 대체 뭐가 문제인지 모르겠다.
  main:
    web-application-type: reactive

server:
  port: 8181

security:
  jwks_uri: "http://localhost:8080/realms/spring-msa-realm/protocol/openid-connect/certs"