spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://config-server:8888
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: db_product
      authentication-database: admin
      username: root
      password: root

server:
  port: 8080