server:
  port: 8080
spring:
  config:
    import: optional:configserver:http://config-server:8888

  datasource:
    url: jdbc://postgresql://postgres:5432/inventory-service
    username: root
    password: root
